name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.24.0
  firebase_auth: 4.15.0
  cloud_firestore: 4.13.3
  image_picker: 1.0.4
  firebase_storage: 11.5.3
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  geolocator: 10.1.0
  geocoding: 2.1.1
  google_fonts: 6.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

